const FALLBACK={businessName:'ARMEK Su Arıtma',siteLogo:'armek-logo.jpg',heroImage:'/uploads/gemini_generated_image_xmulihxmulihxmul.png',aboutImage:'/uploads/ortimax-600x900w.jpg',heroEyebrow:'ARMEK SU ARITMA SERVİSİ',heroTitle:'Su Arıtma Cihazı Satış, Montaj ve Filtre Değişimi',heroText:'Ev ve iş yerleri için pompalı ve pompasız cihaz seçenekleri, filtre değişimi ve teknik servis.',phoneDisplay:'0552 522 35 75',phoneLink:'905525223575',whatsappMessage:'Merhaba, su arıtma hizmetleri hakkında bilgi almak istiyorum.',campaignVisible:true,campaignTitle:'Su Arıtma Cihazı Kampanyası',campaignText:'Nakit ödemeye özel kampanyalı fiyatlar.',campaignImage:'armek-kampanya.jpg',pricesVisible:true,prices:[],services:[],areas:[],faqs:[],facebook:'#',instagram:'#',addressText:'Antalya',footerText:'ARMEK Su Arıtma Cihazları'};
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function getContent(){try{const r=await fetch('/content.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw 0;return {...FALLBACK,...await r.json()}}catch(e){return FALLBACK}}
function setText(id,val){const e=$(id);if(e)e.textContent=val||''}
function setImage(id,src,fallback){const e=$(id);if(!e)return;e.src=src||fallback;e.onerror=()=>{e.onerror=null;e.src=fallback}}
function setLinks(d){const tel=`tel:+${d.phoneLink}`;const wa=`https://wa.me/${d.phoneLink}?text=${encodeURIComponent(d.whatsappMessage||'')}`;['callTop','callHero','callContact'].forEach(id=>{const e=$(id);if(e){e.href=tel;if(id!=='callTop')e.textContent=d.phoneDisplay}});['whatsappHero','whatsappAbout','whatsappContact','floatingWhatsapp'].forEach(id=>{const e=$(id);if(e)e.href=wa});$('facebookTop').href=d.facebook||'#';$('instagramTop').href=d.instagram||'#'}
function render(d){['heroEyebrow','heroTitle','heroText','campaignTitle','campaignText','addressText','footerText'].forEach(k=>setText(k,d[k]));setLinks(d);setImage('headerLogo',d.siteLogo,'armek-logo.jpg');setImage('footerLogo',d.siteLogo,'armek-logo.jpg');setImage('heroImage',d.heroImage,'uploads/gemini_generated_image_xmulihxmulihxmul.png');setImage('aboutImage',d.aboutImage,'uploads/ortimax-600x900w.jpg');setImage('campaignImage',d.campaignImage,'armek-kampanya.jpg');$('favicon').href=d.siteLogo||'armek-logo.jpg';$('kampanya').style.display=d.campaignVisible===false?'none':'';const prices=Array.isArray(d.prices)?d.prices:[];$('prices').style.display=d.pricesVisible===false?'none':'grid';$('prices').innerHTML=prices.map(x=>`<article class="price-card"><h3>${esc(x.title)}</h3><div class="price">${esc(x.price)}</div><p>${esc(x.note)}</p></article>`).join('');const icons=['◌','◇','⌂','⚙'];$('services').innerHTML=(d.services||[]).map((x,i)=>`<article class="service-card"><div class="service-icon">${icons[i%icons.length]}</div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('');$('areas').innerHTML=(d.areas||[]).map(x=>`<span>${esc(x)}</span>`).join('');$('faqs').innerHTML=(d.faqs||[]).map(x=>`<div class="faq"><button aria-expanded="false">${esc(x.q)}</button><p>${esc(x.a)}</p></div>`).join('');document.querySelectorAll('.faq button').forEach(b=>b.onclick=()=>{const p=b.parentElement;p.classList.toggle('open');b.setAttribute('aria-expanded',p.classList.contains('open'))})}
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.main-nav');menu.onclick=()=>{nav.classList.toggle('open');menu.setAttribute('aria-expanded',nav.classList.contains('open'))};nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));$('year').textContent=new Date().getFullYear();getContent().then(render);
if(window.netlifyIdentity)window.netlifyIdentity.on('init',user=>{if(!user)window.netlifyIdentity.on('login',()=>location.href='/admin/')});
