import fs from 'node:fs';
import path from 'node:path';

const ROOT=process.cwd();
const OUT=path.join(ROOT,'_site');
const SITE='https://armeksuaritma.com.tr';
const now=new Date().toISOString().slice(0,10);

const read=(name,fallback={})=>{try{return JSON.parse(fs.readFileSync(path.join(ROOT,name),'utf8'))}catch{return fallback}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const strip=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/[#*_`>\[\]()!-]/g,' ').replace(/\s+/g,' ').trim();
const slugify=value=>String(value||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'detay';
const absolute=u=>u?new URL(u,SITE).href:`${SITE}/armek-logo.jpg`;
const featureList=p=>{const a=[];(p.features||[]).forEach(x=>{const v=typeof x==='string'?x:x?.item;if(v)a.push(v)});String(p.featureText||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(x=>{if(!a.includes(x))a.push(x)});return a};
const photos=o=>{const a=[];if(o.image)a.push(o.image);(o.images||[]).forEach(x=>{const v=typeof x==='string'?x:x?.image;if(v&&!a.includes(v))a.push(v)});return a};
const unique=(a,b,key)=>{const m=new Map();[...(a||[]),...(b||[])].forEach((x,i)=>{if(!x)return;m.set(String(x.slug||x[key]||x.title||x.name||i).toLocaleLowerCase('tr-TR'),x)});return [...m.values()]};
const mkdir=p=>fs.mkdirSync(p,{recursive:true});
const write=(rel,html)=>{const f=path.join(OUT,rel);mkdir(path.dirname(f));fs.writeFileSync(f,html)};

const content=read('content.json',{}), home=read('home.json',{}), settings=read('settings.json',{}), seo=read('seo.json',{});
const productData=read('products.json',{products:[]}), workData=read('works.json',{works:[]}), serviceData=read('services.json',{services:[]}), faqData=read('faqs.json',{faqs:[]}), articlesData=read('articles.json',{articles:[]});
const data={...content,...home,...settings,...seo};
const products=unique(content.products,productData.products,'name').filter(x=>x?.active!==false);
const works=unique(content.works,workData.works,'title').filter(x=>x?.active!==false);
const services=unique(content.services,serviceData.services,'title').filter(x=>x?.active!==false);
const faqs=unique(content.faqs,faqData.faqs,'q').filter(x=>x?.active!==false);
const articles=(articlesData.articles||[]).filter(x=>x?.active!==false);

fs.rmSync(OUT,{recursive:true,force:true});mkdir(OUT);
const skip=new Set(['.git','.github','node_modules','_site','build.mjs','package.json','package-lock.json','README-SEO-PRO.md']);
function copyTree(src,dst){for(const ent of fs.readdirSync(src,{withFileTypes:true})){if(skip.has(ent.name))continue;const a=path.join(src,ent.name),b=path.join(dst,ent.name);if(ent.isDirectory()){mkdir(b);copyTree(a,b)}else fs.copyFileSync(a,b)}}
copyTree(ROOT,OUT);

const phone=String(data.phoneLink||'905525223575').replace(/\D/g,'');
const display=data.phoneDisplay||'0552 522 35 75';
const logo=absolute(data.logoImage||'/armek-logo.jpg');
const business=data.businessName||'ARMEK Su Arıtma';
const description=data.seoDescription||data.heroText||'Antalya su arıtma cihazı satışı, montaj, filtre değişimi ve teknik servis.';
const analytics='G-DQBRPFTJ5J';

const md=s=>esc(s||'').replace(/\n\n+/g,'</p><p>').replace(/\n/g,'<br>');
const analyticsTag=`<script async src="https://www.googletagmanager.com/gtag/js?id=${analytics}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${analytics}');</script>`;
const localBusiness={"@context":"https://schema.org","@type":"LocalBusiness","@id":`${SITE}/#business`,name:business,url:`${SITE}/`,logo,image:absolute(data.seoImage||data.logoImage||'/armek-logo.jpg'),telephone:display,email:data.email||undefined,address:{"@type":"PostalAddress",streetAddress:data.streetAddress||undefined,addressLocality:data.addressDistrict||'Antalya',addressRegion:'Antalya',postalCode:data.postalCode||undefined,addressCountry:'TR'},areaServed:(data.areas||[]).map(x=>typeof x==='string'?x:x.item).filter(Boolean),openingHours:data.openingHours||undefined,sameAs:[data.facebook,data.instagram].filter(Boolean)};
const clean=o=>JSON.parse(JSON.stringify(o,(k,v)=>v===undefined||v===''?undefined:v));

function shell({title,desc,url,image,body,schema,type='website'}){return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${url}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${absolute(image||logo)}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${logo}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/seo-page.css">${analyticsTag}<script type="application/ld+json">${JSON.stringify(clean(schema))}</script></head><body><header class="seo-header"><div class="seo-container"><a href="/" class="seo-logo"><img src="${logo}" alt="${esc(business)}"></a><nav><a href="/">Ana Sayfa</a><a href="/urunler/">Ürünler</a><a href="/yaptigimiz-isler/">Yaptığımız İşler</a><a href="/hizmetler/">Hizmetler</a><a href="/bilgi/">Bilgi Merkezi</a><a class="call" href="tel:+${phone}">${esc(display)}</a></nav></div></header><main>${body}</main><footer class="seo-footer"><div class="seo-container"><div><strong>${esc(business)}</strong><p>${esc(data.addressText||'Antalya')}</p></div><div><a href="tel:+${phone}">${esc(display)}</a><a href="https://wa.me/${phone}" target="_blank" rel="noopener">WhatsApp</a></div></div></footer><script src="/seo-page.js"></script></body></html>`}
const breadcrumb=(items)=>`<nav class="breadcrumbs" aria-label="İçerik yolu">${items.map((x,i)=>i===items.length-1?`<span>${esc(x.name)}</span>`:`<a href="${x.url}">${esc(x.name)}</a><b>›</b>`).join('')}</nav>`;
const crumbsSchema=items=>({"@type":"BreadcrumbList",itemListElement:items.map((x,i)=>({"@type":"ListItem",position:i+1,name:x.name,item:x.url?`${SITE}${x.url}`:undefined}))});

const urls=[{loc:`${SITE}/`,lastmod:now,images:[]}];

// Product listing
const productCards=products.map(p=>{const s=p.slug||slugify(p.name);return `<article class="listing-card"><a href="/urun/${s}/"><img loading="lazy" src="${esc(p.image||photos(p)[0]||'/armek-logo.jpg')}" alt="${esc(p.name)}"><span>${esc(p.category||'Ürün')}</span><h2>${esc(p.name)}</h2><ul>${featureList(p).slice(0,5).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></a><a class="wa" href="https://wa.me/${phone}?text=${encodeURIComponent(`${p.name||'Ürün'} için fiyat bilgisi almak istiyorum.`)}">Fiyat Sor</a></article>`}).join('');
write('urunler/index.html',shell({title:`Su Arıtma Cihazları ve Filtreler | ${business}`,desc:'Antalya için su arıtma cihazları, filtreler, tanklar ve yedek parçaları inceleyin.',url:`${SITE}/urunler/`,image:products[0]?.image,body:`<section class="seo-hero"><div class="seo-container">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Ürünler'}])}<p class="eyebrow">ÜRÜN KATALOĞU</p><h1>Su Arıtma Cihazları, Filtreler ve Yedek Parçalar</h1><p>Antalya’da satış, montaj ve teknik servis desteğiyle ürün seçeneklerimizi inceleyin.</p></div></section><section class="seo-section"><div class="seo-container listing-grid">${productCards}</div></section>`,schema:{"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Ürünler',url:'/urunler/'}]),{"@type":"CollectionPage",name:'Ürünler',url:`${SITE}/urunler/`} ]}}));
urls.push({loc:`${SITE}/urunler/`,lastmod:now,images:products.map(p=>absolute(p.image)).filter(Boolean)});

for(const p of products){const s=p.slug||slugify(p.name),u=`${SITE}/urun/${s}/`,features=featureList(p),pics=photos(p);const title=p.seoTitle||`${p.name} | Antalya Su Arıtma | ${business}`;const desc=strip(p.seoDescription||p.description||`${p.name} su arıtma ürünü. Antalya satış, montaj ve servis desteği.`).slice(0,160);const schema={"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Ürünler',url:'/urunler/'},{name:p.name,url:`/urun/${s}/`}]),{"@type":"Product","@id":`${u}#product`,name:p.name,image:pics.map(absolute),description:strip(p.longDescription||p.description||features.join(', ')),brand:p.brand?{"@type":"Brand",name:p.brand}:undefined,model:p.model||undefined,url:u}]};const gallery=pics.map((x,i)=>`<button class="gallery-item" data-full="${esc(x)}"><img ${i?'loading="lazy"':''} src="${esc(x)}" alt="${esc(p.name)} ${i+1}"></button>`).join('');const related=products.filter(x=>x!==p&&x.category===p.category).slice(0,3).map(x=>`<a class="related" href="/urun/${x.slug||slugify(x.name)}/"><img loading="lazy" src="${esc(x.image||'/armek-logo.jpg')}" alt="${esc(x.name)}"><strong>${esc(x.name)}</strong></a>`).join('');const body=`<section class="seo-section"><div class="seo-container">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Ürünler',url:'/urunler/'},{name:p.name}])}<div class="detail-grid"><div><div class="gallery">${gallery}</div></div><article class="detail-copy"><p class="eyebrow">${esc(p.category||'ÜRÜN')}</p><h1>${esc(p.name)}</h1>${p.description?`<p class="lead">${esc(p.description)}</p>`:''}<h2>Ürün Özellikleri</h2><ul class="feature-list">${features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${p.longDescription?`<section class="long-copy"><h2>Ürün Hakkında</h2><p>${md(p.longDescription)}</p></section>`:''}<div class="cta-row"><a class="primary" href="https://wa.me/${phone}?text=${encodeURIComponent(`${p.name} hakkında fiyat ve montaj bilgisi almak istiyorum.`)}">WhatsApp’tan Fiyat Al</a><a class="secondary" href="tel:+${phone}">${esc(display)}</a></div></article></div>${related?`<section class="related-section"><h2>Benzer Ürünler</h2><div class="related-grid">${related}</div></section>`:''}</div></section>`;write(`urun/${s}/index.html`,shell({title,desc,url:u,image:pics[0],body,schema,type:'product'}));urls.push({loc:u,lastmod:now,images:pics.map(absolute)})}

// Works listing and detail
const workCards=works.map(w=>{const s=w.slug||slugify(w.title);return `<article class="listing-card"><a href="/isler/${s}/"><img loading="lazy" src="${esc(w.image||'/armek-logo.jpg')}" alt="${esc(w.title)}"><span>${esc(w.category||'Uygulama')}</span><h2>${esc(w.title)}</h2><p>${esc(w.location||'Antalya')} ${w.date?`• ${esc(w.date)}`:''}</p></a></article>`}).join('');
write('yaptigimiz-isler/index.html',shell({title:`Antalya Su Arıtma Montaj ve Servis Çalışmaları | ${business}`,desc:'Antalya’da gerçekleştirdiğimiz su arıtma cihazı montajı, filtre değişimi ve teknik servis çalışmalarını inceleyin.',url:`${SITE}/yaptigimiz-isler/`,image:works[0]?.image,body:`<section class="seo-hero"><div class="seo-container">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Yaptığımız İşler'}])}<p class="eyebrow">GERÇEK UYGULAMALAR</p><h1>Antalya’da Yaptığımız Su Arıtma Çalışmaları</h1><p>Montaj, filtre değişimi, cihaz satışı ve teknik servis örnekleri.</p></div></section><section class="seo-section"><div class="seo-container listing-grid">${workCards}</div></section>`,schema:{"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Yaptığımız İşler',url:'/yaptigimiz-isler/'}]),{"@type":"CollectionPage",name:'Yaptığımız İşler',url:`${SITE}/yaptigimiz-isler/`} ]}}));urls.push({loc:`${SITE}/yaptigimiz-isler/`,lastmod:now,images:works.map(w=>absolute(w.image)).filter(Boolean)});
for(const w of works){const s=w.slug||slugify(w.title),u=`${SITE}/isler/${s}/`,pics=photos(w);const title=w.seoTitle||`${w.title} | ${w.location||'Antalya'} | ${business}`;const desc=strip(w.seoDescription||w.text||`${w.title}. Antalya su arıtma montaj, filtre değişimi ve teknik servis çalışması.`).slice(0,160);const schema={"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Yaptığımız İşler',url:'/yaptigimiz-isler/'},{name:w.title,url:`/isler/${s}/`}]),{"@type":"Service",name:w.title,description:strip(w.longDescription||w.text||''),provider:{"@id":`${SITE}/#business`},areaServed:w.location||'Antalya',serviceType:w.category||'Su arıtma hizmeti',image:pics.map(absolute),url:u}]};const gallery=pics.map((x,i)=>`<button class="gallery-item" data-full="${esc(x)}"><img ${i?'loading="lazy"':''} src="${esc(x)}" alt="${esc(w.title)} ${i+1}"></button>`).join('');const body=`<section class="seo-section"><div class="seo-container">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Yaptığımız İşler',url:'/yaptigimiz-isler/'},{name:w.title}])}<div class="detail-grid"><div class="gallery">${gallery}</div><article class="detail-copy"><p class="eyebrow">${esc(w.category||'UYGULAMA')}</p><h1>${esc(w.title)}</h1><div class="meta"><span>📍 ${esc(w.location||'Antalya')}</span>${w.date?`<span>🗓 ${esc(w.date)}</span>`:''}</div>${w.text?`<p class="lead">${esc(w.text)}</p>`:''}${w.longDescription?`<section class="long-copy"><h2>Yapılan İşlem</h2><p>${md(w.longDescription)}</p></section>`:''}<div class="cta-row"><a class="primary" href="https://wa.me/${phone}?text=${encodeURIComponent(`${w.title} benzeri bir hizmet için bilgi almak istiyorum.`)}">Benzer Hizmet İçin Yaz</a><a class="secondary" href="tel:+${phone}">${esc(display)}</a></div></article></div></div></section>`;write(`isler/${s}/index.html`,shell({title,desc,url:u,image:pics[0],body,schema}));urls.push({loc:u,lastmod:w.date||now,images:pics.map(absolute)})}

// Services
const serviceCards=services.map(s=>`<article class="text-card"><h2><a href="/hizmet/${s.slug||slugify(s.title)}/">${esc(s.title)}</a></h2><p>${esc(s.text||'')}</p></article>`).join('');
write('hizmetler/index.html',shell({title:`Antalya Su Arıtma Servisi ve Filtre Değişimi | ${business}`,desc:'Antalya su arıtma cihazı satışı, montajı, filtre değişimi ve teknik servis hizmetleri.',url:`${SITE}/hizmetler/`,body:`<section class="seo-hero"><div class="seo-container">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Hizmetler'}])}<p class="eyebrow">ANTALYA GENELİ</p><h1>Su Arıtma Satış, Montaj, Filtre Değişimi ve Teknik Servis</h1><p>${esc(description)}</p></div></section><section class="seo-section"><div class="seo-container text-grid">${serviceCards}</div></section>`,schema:{"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Hizmetler',url:'/hizmetler/'}]) ]}}));urls.push({loc:`${SITE}/hizmetler/`,lastmod:now,images:[]});
for(const s of services){const slug=s.slug||slugify(s.title),u=`${SITE}/hizmet/${slug}/`,title=s.seoTitle||`${s.title} Antalya | ${business}`,desc=strip(s.seoDescription||s.text||title).slice(0,160);write(`hizmet/${slug}/index.html`,shell({title,desc,url:u,body:`<section class="seo-section"><div class="seo-container narrow">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Hizmetler',url:'/hizmetler/'},{name:s.title}])}<p class="eyebrow">ANTALYA SU ARITMA HİZMETİ</p><h1>${esc(s.title)}</h1><p class="lead">${esc(s.text||'')}</p>${s.longDescription?`<section class="long-copy"><h2>Hizmet Detayları</h2><p>${md(s.longDescription)}</p></section>`:''}<h2>Neden ARMEK?</h2><p>Antalya genelinde doğru ürün seçimi, temiz montaj, periyodik bakım ve hızlı teknik destek sunuyoruz.</p><div class="cta-row"><a class="primary" href="https://wa.me/${phone}?text=${encodeURIComponent(`${s.title} hizmeti hakkında bilgi almak istiyorum.`)}">WhatsApp’tan Bilgi Al</a><a class="secondary" href="tel:+${phone}">${esc(display)}</a></div></div></section>`,schema:{"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Hizmetler',url:'/hizmetler/'},{name:s.title,url:`/hizmet/${slug}/`}]),{"@type":"Service",name:s.title,description:s.text,provider:{"@id":`${SITE}/#business`},areaServed:'Antalya',url:u}]}}));urls.push({loc:u,lastmod:now,images:[]})}

// Articles
const articleCards=articles.map(a=>`<article class="listing-card"><a href="/bilgi/${a.slug||slugify(a.title)}/">${a.image?`<img loading="lazy" src="${esc(a.image)}" alt="${esc(a.title)}">`:''}<h2>${esc(a.title)}</h2><p>${esc(a.summary||'')}</p></a></article>`).join('');
write('bilgi/index.html',shell({title:`Su Arıtma Bilgi Merkezi | ${business}`,desc:'Su arıtma cihazları, filtre değişimi, bakım ve temiz su hakkında faydalı bilgiler.',url:`${SITE}/bilgi/`,body:`<section class="seo-hero"><div class="seo-container">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Bilgi Merkezi'}])}<p class="eyebrow">FAYDALI BİLGİLER</p><h1>Su Arıtma Bilgi Merkezi</h1><p>Doğru cihaz seçimi, filtre bakımı ve kullanım hakkında özgün rehberler.</p></div></section><section class="seo-section"><div class="seo-container listing-grid">${articleCards||'<p>Bilgi yazıları yakında eklenecek.</p>'}</div></section>`,schema:{"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Bilgi Merkezi',url:'/bilgi/'}]) ]}}));urls.push({loc:`${SITE}/bilgi/`,lastmod:now,images:[]});
for(const a of articles){const s=a.slug||slugify(a.title),u=`${SITE}/bilgi/${s}/`,title=a.seoTitle||`${a.title} | ${business}`,desc=strip(a.seoDescription||a.summary||a.body).slice(0,160);write(`bilgi/${s}/index.html`,shell({title,desc,url:u,image:a.image,body:`<article class="seo-section"><div class="seo-container narrow">${breadcrumb([{name:'Ana Sayfa',url:'/'},{name:'Bilgi Merkezi',url:'/bilgi/'},{name:a.title}])}<p class="eyebrow">SU ARITMA REHBERİ</p><h1>${esc(a.title)}</h1>${a.image?`<img class="article-cover" src="${esc(a.image)}" alt="${esc(a.title)}">`:''}<p class="lead">${esc(a.summary||'')}</p><div class="long-copy"><p>${md(a.body)}</p></div><div class="cta-row"><a class="primary" href="https://wa.me/${phone}">Sorunuzu WhatsApp’tan Sorun</a></div></div></article>`,schema:{"@context":"https://schema.org","@graph":[localBusiness,crumbsSchema([{name:'Ana Sayfa',url:'/'},{name:'Bilgi Merkezi',url:'/bilgi/'},{name:a.title,url:`/bilgi/${s}/`}]),{"@type":"Article",headline:a.title,description:desc,image:a.image?absolute(a.image):undefined,datePublished:a.date||now,dateModified:a.date||now,author:{"@type":"Organization",name:business},publisher:{"@id":`${SITE}/#business`},mainEntityOfPage:u}]},type:'article'}));urls.push({loc:u,lastmod:a.date||now,images:a.image?[absolute(a.image)]:[]})}

// Homepage static metadata/schema injected into copied index
let index=fs.readFileSync(path.join(OUT,'index.html'),'utf8');
const homeSchema={"@context":"https://schema.org","@graph":[localBusiness,{"@type":"WebSite","@id":`${SITE}/#website`,url:`${SITE}/`,name:business,inLanguage:'tr-TR',publisher:{"@id":`${SITE}/#business`}},faqs.length?{"@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.q,acceptedAnswer:{"@type":"Answer",text:f.a}}))}:undefined].filter(Boolean)};
index=index.replace('<script id="structuredData" type="application/ld+json"></script>',`<script id="structuredData" type="application/ld+json">${JSON.stringify(clean(homeSchema))}</script>`);
index=index.replace('</head>',`<link rel="alternate" type="application/rss+xml" title="ARMEK Bilgi Merkezi" href="/feed.xml"></head>`);
fs.writeFileSync(path.join(OUT,'index.html'),index);

// Sitemap with image entries
const xml=urls.map(x=>`<url><loc>${x.loc}</loc><lastmod>${String(x.lastmod||now).slice(0,10).split('.').reverse().join('-')}</lastmod>${(x.images||[]).slice(0,10).map(i=>`<image:image><image:loc>${i}</image:loc></image:image>`).join('')}</url>`).join('');
fs.writeFileSync(path.join(OUT,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">${xml}</urlset>`);
fs.writeFileSync(path.join(OUT,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: ${SITE}/sitemap.xml\n`);
fs.writeFileSync(path.join(OUT,'CNAME'),'armeksuaritma.com.tr\n');
fs.writeFileSync(path.join(OUT,'.nojekyll'),'');
const feed=articles.slice(0,20).map(a=>{const s=a.slug||slugify(a.title);return `<item><title>${esc(a.title)}</title><link>${SITE}/bilgi/${s}/</link><guid>${SITE}/bilgi/${s}/</guid><description>${esc(a.summary||'')}</description><pubDate>${new Date(a.date||Date.now()).toUTCString()}</pubDate></item>`}).join('');
fs.writeFileSync(path.join(OUT,'feed.xml'),`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>${esc(business)} Bilgi Merkezi</title><link>${SITE}/bilgi/</link><description>Su arıtma hakkında faydalı bilgiler</description>${feed}</channel></rss>`);
console.log(`SEO build tamamlandı: ${urls.length} indekslenebilir URL üretildi.`);
