const qs=new URLSearchParams(location.search);const type=qs.get('tip');const wanted=qs.get('slug')||'';const root=document.getElementById('detailRoot');
const slugify=v=>String(v||'').toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fetchJson=async u=>{try{const r=await fetch(`${u}?v=${Date.now()}`);return r.ok?await r.json():{}}catch{return {}}};
const merge=(a=[],b=[],key)=>{const m=new Map();[...a,...b].forEach((x,i)=>{if(!x)return;m.set(String(x.slug||x[key]||i).toLocaleLowerCase('tr-TR'),x)});return [...m.values()]};
const photos=o=>{const a=[];if(o.image)a.push(o.image);(o.images||[]).forEach(x=>{const v=typeof x==='string'?x:x?.image;if(v&&!a.includes(v))a.push(v)});return a};
const features=p=>{const a=[];(p.features||[]).forEach(x=>{const v=typeof x==='string'?x:x?.item;if(v)a.push(v)});String(p.featureText||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(x=>{if(!a.includes(x))a.push(x)});return a};
function setMeta(title,desc,image){document.title=title;document.querySelector('meta[name="description"]').content=desc||'';document.getElementById('canonical').href=location.href;const data={"@context":"https://schema.org","@type":type==='urun'?'Product':'Service',name:title,description:desc,image:image?new URL(image,location.origin).href:undefined,url:location.href};const n=document.createElement('script');n.type='application/ld+json';n.textContent=JSON.stringify(data);document.head.appendChild(n)}
function productView(p,phone){const pics=photos(p),fs=features(p),main=pics[0]||'/armek-logo.jpg';setMeta(`${p.name} | Antalya Su Arıtma | ARMEK`,p.seoDescription||p.description||fs.join(', '),main);root.innerHTML=`<div class="detail-grid2"><section class="detail-media"><div class="detail-main-image"><img id="mainPhoto" src="${esc(main)}" alt="${esc(p.name)}"></div><div class="detail-thumbs">${pics.map((x,i)=>`<button class="detail-thumb ${i===0?'active':''}" data-src="${esc(x)}"><img src="${esc(x)}" alt="${esc(p.name)} ${i+1}"></button>`).join('')}</div></section><article class="detail-copy2"><span class="product-category">${esc(p.category||'Ürün')}</span><h1>${esc(p.name)}</h1>${p.description?`<p class="detail-lead">${esc(p.description)}</p>`:''}<h2>Ürün Özellikleri</h2><ul class="detail-features">${fs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${p.longDescription?`<h2>Ürün Hakkında</h2><p class="detail-text">${esc(p.longDescription)}</p>`:''}<div class="detail-actions"><a class="detail-wa" target="_blank" rel="noopener" href="https://wa.me/${phone}?text=${encodeURIComponent(`${p.name} hakkında fiyat ve montaj bilgisi almak istiyorum.`)}">WhatsApp'tan Fiyat Al</a><a class="detail-call" href="tel:+${phone}">Hemen Ara</a></div></article></div>`;document.querySelectorAll('.detail-thumb').forEach(b=>b.onclick=()=>{document.getElementById('mainPhoto').src=b.dataset.src;document.querySelectorAll('.detail-thumb').forEach(x=>x.classList.remove('active'));b.classList.add('active')});gtag('event','view_product',{product_name:p.name})}
function workView(w,phone){const pics=photos(w),main=pics[0]||'/armek-logo.jpg';setMeta(`${w.title} | ${w.location||'Antalya'} | ARMEK`,w.seoDescription||w.text||w.longDescription||'',main);root.innerHTML=`<div class="detail-grid2"><section class="detail-media"><div class="detail-gallery-work">${pics.map(x=>`<img src="${esc(x)}" alt="${esc(w.title)}">`).join('')}</div></section><article class="detail-copy2"><span class="product-category">${esc(w.category||'Yaptığımız İş')}</span><h1>${esc(w.title)}</h1><div class="detail-meta"><span>📍 ${esc(w.location||'Antalya')}</span>${w.date?`<span>🗓 ${esc(w.date)}</span>`:''}</div>${w.text?`<p class="detail-lead">${esc(w.text)}</p>`:''}${w.longDescription?`<h2>Yapılan İşlem</h2><p class="detail-text">${esc(w.longDescription)}</p>`:''}<div class="detail-actions"><a class="detail-wa" target="_blank" rel="noopener" href="https://wa.me/${phone}?text=${encodeURIComponent(`${w.title} benzeri hizmet için bilgi almak istiyorum.`)}">WhatsApp'tan Bilgi Al</a><a class="detail-call" href="tel:+${phone}">Hemen Ara</a></div></article></div>`;gtag('event','view_work',{work_title:w.title})}
(async()=>{const [content,products,works,settings]=await Promise.all([fetchJson('/content.json'),fetchJson('/products.json'),fetchJson('/works.json'),fetchJson('/settings.json')]);const data={...content,...settings};const phone=String(data.phoneLink||'905525223575').replace(/\D/g,'');if(data.logoImage)document.getElementById('detailLogo').src=data.logoImage;if(type==='urun'){const list=merge(content.products,products.products,'name');const item=list.find(x=>(x.slug||slugify(x.name))===wanted);if(item)return productView(item,phone)}if(type==='is'){const list=merge(content.works,works.works,'title');const item=list.find(x=>(x.slug||slugify(x.title))===wanted);if(item)return workView(item,phone)}root.innerHTML='<div class="detail-error"><h1>İçerik bulunamadı</h1><p>Bu kayıt silinmiş veya adresi değişmiş olabilir.</p><a class="button primary" href="/">Ana sayfaya dön</a></div>'})();
